version: '3'
services:
  web:
    build: .
    container_name: flask_web
    ports:
      - "5000:5000"
    volumes:
      - ./code:/code
    depends_on:
      - neo4j2
      - postgres
      - mongodb
      - redis
    environment:
      - MONGO_URI=mongodb://mongodb:27017/ecommerc
  neo4j2:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687" 
    environment:
      NEO4J_AUTH: 'neo4j/adminpass'
  postgres:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    container_name: postgres_web
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpwd
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
  redis:
    image: redislabs/redismod
    container_name: redis_3
    ports:
      - "6379:6379"
volumes:
  mongo_data:
    driver: local